### ISSUE TITLE
샤키밥 요구사항

### ISSUE THREAD

**Issue by sunmangul** [sunrabbit123/Snow_shaki#11]
나이스에서 제공 받는 급식 데이터의 문자열에서 급식의 이름으로 들어가는 숫자는 필터링 안 되게 해주세요.
> ex) `10곡 잡곡밥 -> 곡잡곡밥`이 되지 않도록

**Comment by sunrabbit123** [comment]
헉

**Comment by sunrabbit123** [comment]
![image](https://user-images.githubusercontent.com/64676070/164605875-0f20f0a4-b990-4426-93d6-991cc08bfed2.png)

컷

곧 배포될 예정입니다.
